/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10520058;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mahasiswa
 */
public class FAnggota extends javax.swing.JFrame {
    
    Connection conn;
    
    DefaultTableModel tabModel;

    /**
     * Creates new form FAnggota
     */
    public FAnggota() {
        initComponents();
        conn = Koneksi.getConnection();
        setJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        txtNoAnggota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Anggota");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        addButton.setText("Tambah");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Batal");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelAnggota);

        jLabel4.setText("Cari Berdasarkan");

        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Anggota", "Nama" }));

        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Tutup");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(previewButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(saveButton)
                    .addComponent(editButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton)
                    .addComponent(previewButton)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (saveButton.getText().equalsIgnoreCase("Simpan"))
            simpanData();
        else
            updateData();
        
        txtNoAnggota.setEnabled(false);
        txtNama.setEnabled(false);
        txtAlamat.setEnabled(false);
        
        addButton.setEnabled(true);
        saveButton.setEnabled(false);
        editButton.setEnabled(true);
        cancelButton.setEnabled(false);
        deleteButton.setEnabled(true);
        closeButton.setEnabled(true); 
    }//GEN-LAST:event_saveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        txtNoAnggota.setEnabled(false); // txtNoAnggota Tidak Aktif
        txtNama.setEnabled(true); // txtNama Aktif
        txtAlamat.setEnabled(true); // txtAlamat Aktif
        saveButton.setText("Update"); // Merubah Teks Tombol Simpan
        
        addButton.setEnabled(false);
        saveButton.setEnabled(true);
        editButton.setEnabled(false);
        cancelButton.setEnabled(true);
        deleteButton.setEnabled(false);
        closeButton.setEnabled(false);
        
        // Memanggil Method ambilData_dari_JTable()
        ambilData_dari_JTable();
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        txtNoAnggota.setEnabled(true); // txtNoAnggota Tidak Aktif
        txtNama.setEnabled(true); // txtNama Aktif
        txtAlamat.setEnabled(true); // txtAlamat Aktif
        
        txtNoAnggota.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        
        addButton.setEnabled(false);
        saveButton.setEnabled(true);
        editButton.setEnabled(false);
        cancelButton.setEnabled(true);
        deleteButton.setEnabled(false);
        closeButton.setEnabled(false);

    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        txtNoAnggota.setEnabled(true); // txtNoAnggota Tidak Aktif
        txtNama.setEnabled(true); // txtNama Aktif
        txtAlamat.setEnabled(true); // txtAlamat Aktif
        
        txtNoAnggota.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        
        saveButton.setText("Simpan"); 
        
        addButton.setEnabled(true);
        saveButton.setEnabled(false);
        editButton.setEnabled(true);
        cancelButton.setEnabled(false);
        deleteButton.setEnabled(true);
        closeButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String sql;
        int pilih = cbCari.getSelectedIndex();
        try {
            if(pilih == 0)
                sql ="Select * from anggota WHERE no_anggota ='" +txtCari.getText() + "'";
            else
                sql ="Select * from anggota WHERE nama Like '%" +txtCari.getText() + "%'";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            hapusIsiJTable();
            int no = 0;
            while (rs.next()) {
            no++;
                String NoAnggota = rs.getString("no_anggota");
                String Nama = rs.getString("nama");
                String Alamat = rs.getString("alamat");
                Object [] data = {no,NoAnggota, Nama, Alamat};
                tabModel.addRow(data);
            }
            if (tabModel.getRowCount() > 0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");
        } catch (SQLException se) {} 
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        hapusData();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        previewData();
    }//GEN-LAST:event_previewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FAnggota().setVisible(true);
        });
    }
    
    private void setJTable(){
        String [] JudulKolom={"No","No Anggota","Nama Anggota","Alamat"};
        tabModel = new DefaultTableModel(null, JudulKolom){
            boolean[] canEdit = new boolean [] { false, false, false, false};
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tabelAnggota.setModel(tabModel);
        tabelAnggota.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelAnggota.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabelAnggota.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelAnggota.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelAnggota.getColumnModel().getColumn(3).setPreferredWidth(300);
        getData();
    }
    
    private void getData() {
        try {
            // Membuat perintah sql
            String sql="SELECT * FROM anggota";
            PreparedStatement st=conn.prepareStatement(sql); // import java.sql.PreparedStatement
            //Membuat Variabel Bertipe ResulSet
            //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
            ResultSet rs = st.executeQuery(); // import java.sql.ResultSet;
            // Menampilkan ke JTable melalui tabModel
            String NoAnggota,Nama,Alamat;
            int no=0;
            while(rs.next()) {
                no=no+1;
                NoAnggota=rs.getString("no_anggota");
                Nama=rs.getString("nama");
                Alamat=rs.getString("alamat");
                Object Data[]={no,NoAnggota,Nama,Alamat};
                tabModel.addRow(Data);
            }
        } catch (SQLException sqle) {
            System.out.println("Proses Query Gagal = " + sqle);
            System.exit(0);
        } catch(Exception e) {
            System.out.println("Koneksi Access Gagal " + e.getMessage());
            System.exit(0);
        }
    }
    
    void simpanData() {
        try {
            String sql="INSERT INTO anggota VALUES(?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtNoAnggota.getText());
            st.setString(2, txtNama.getText());
            st.setString(3, txtAlamat.getText());
            int rs = st.executeUpdate();
            if(rs > 0) {
                JOptionPane.showMessageDialog(this,"Input Berhasil");
                setJTable();
            }
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(this,"Input Gagal = " + sqle.getMessage());
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,"Koneksi Gagal " + e.getMessage());
        }
    }
    
    void ambilData_dari_JTable() {
        int row = tabelAnggota.getSelectedRow();
        // Mengambil data yang dipilih pada JTable
        String NoAnggota = tabModel.getValueAt(row, 1).toString();
        String Nama = tabModel.getValueAt(row, 2).toString();
        String Alamat = tabModel.getValueAt(row, 3).toString();

        txtNoAnggota.setText(NoAnggota);
        txtNama.setText(Nama);
        txtAlamat.setText(Alamat);
    }
    
    public void hapusIsiJTable() {
        int row = tabModel.getRowCount();
        for (int i = 0; i < row; i++) {
            tabModel.removeRow(0);
        }
    }
    // Method Untuk Menampilkan Data dari tabel Anggota Ke JTable
    public void tampilDataKeJTable() {
        hapusIsiJTable();
        try {
            String sql="SELECT * FROM anggota";
            PreparedStatement st=conn.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            String NoAnggota,Nama,Alamat;
            int no=0;
            while(rs.next()){
                no=no+1;
                NoAnggota=rs.getString("no_anggota");
                Nama=rs.getString("nama");
                Alamat=rs.getString("alamat");
                Object Data[]={no,NoAnggota,Nama,Alamat};
                tabModel.addRow(Data);
            }
        }
        catch (SQLException e) { } // Isi informasi eksepsi
    }
    
    public void updateData() {
        // Konfirmasi sebelum melakukan perubahan data
        int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan No Anggota = '" + txtNoAnggota.getText() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);
        // Apabila tombol Yes ditekan
        if (ok == 0) {
            try {
                String sql ="UPDATE anggota SET nama = ?, alamat = ? WHERE no_anggota = ?";
                PreparedStatement st = conn.prepareStatement(sql);

                st.setString(1, txtNama.getText());
                st.setString(2, txtAlamat.getText());
                st.setString(3, txtNoAnggota.getText());
                int rs=st.executeUpdate();
                if(rs > 0){
                    JOptionPane.showMessageDialog(this,"Edit Data Berhasil");
                    tampilDataKeJTable();
                }
                txtNoAnggota.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
            } catch (SQLException se) {
            
            } // Silahkan tambahkan Sendiri informasi Eksepsi
        }
    }
    
    public void hapusData() {
        // Konfirmasi sebelum melakukan penghapusan data
        ambilData_dari_JTable();
        
        int ok = JOptionPane.showConfirmDialog(
                this,
                "Anda Yakin Ingin Menghapus Data\nDengan No Anggota = '" + txtNoAnggota.getText() +"'",
                "Konfirmasi Menghapus Data",
                JOptionPane.YES_NO_OPTION
        );
        
        if (ok == 0) { // Apabila tombol OK ditekan
            try {
                String sql = "DELETE FROM anggota WHERE no_anggota = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtNoAnggota.getText());
                int rs=st.executeUpdate();
                if(rs > 0) {
                    tampilDataKeJTable();
                    JOptionPane.showMessageDialog(this,"Data Berhasil dihapus");
                }
                txtNoAnggota.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
            } catch (HeadlessException | SQLException se) { // Silahkan tambahkan catch Exception yang lain
                JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
            }
        }
    }
    
    private void previewData() {
        try {
            String reportPath = "/home/irlfdyh/JaspersoftWorkspace/MyReports/Anggota.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            // Do something here
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton previewButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoAnggota;
    // End of variables declaration//GEN-END:variables
}
